# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false
# JDBC
services:
  postgresql
# Изменяет текущую временную зону.
before_install:
  - export TZ=Europe/Moscow
  - date
  # JDBC создание базы данных
  - psql -c 'create database dreamjob;' -U postgres
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN='6b44367a-2dcb-4fb2-a9f3-441304770ccb'

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - roman9628@gmail.com
    on_success: never # default: change
    on_failure: always # default: always